import Head from 'next/head'
import PageTransition2 from "@/components/Layout/Page_Transition2";
import Statement2 from "@/components/About/index2";


export default function About() {
  return (
    <>
      <Head>
        <title>About | Against Low Trends</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTransition2>
        <Statement2 />
      </PageTransition2>
    </>
  )
}