// import Head from 'next/head'
// import PageTransition from "@/components/Layout/Page_Transition";
import Statement from "@/components/About";
import Statement2 from "@/components/About/index2";
import PageTransition from "@/components/Layout/Page_Transition";
import PageTransition2 from "@/components/Layout/Page_Transition2";


export default function About() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <PageTransition2>
        <Statement2 />
      </PageTransition2>
        {/* <div className="h-screen text-black bg-white">
          <h1>About</h1>
          <div className=''>
              <p className=''> Nullam mattis mattis dictum. Praesent sit amet condimentum mi, quis venenatis lectus. Phasellus ac ante id purus viverra hendrerit quis at ex. Donec vitae augue pulvinar augue dictum fermentum dapibus nec tellus.</p>
          </div>
          </div> */}
    </>
  )
}