import Head from 'next/head'
import ContactInfo from "@/components/Contact/index2";
import PageTransition2 from "@/components/Layout/Page_Transition2";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact | Against Low Trends</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTransition2>
        <ContactInfo />
      </PageTransition2>
    </>
  )
}