// import Head from 'next/head'
import Contact3 from "@/components/Contact";
import ContactForm from "@/components/Contact";
import Contact2 from "@/components/Contact/index2";
import PageTransition from "@/components/Layout/Page_Transition";
import PageTransition2 from "@/components/Layout/Page_Transition2";

export default function Contact() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <PageTransition2>
        <Contact3 />
      </PageTransition2>
    </>
  )
}