"use client";

import PageTransition2 from "@/components/Layout/Page_Transition2";
import Home3 from "@/components/Home/index2";
import Home4 from "@/components/Home";


export default function HomePage () {
  return(
    <>
    {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
    <PageTransition2>
      {/* <Home3 /> */}
      <Home4 />
    </PageTransition2>
    </>
  )
};


// "use client";

// import PageTransition2 from "@/components/Layout/Page_Transition2";
// import Home3 from "@/components/Home/index2";
// import Home4 from "@/components/Home";
// import { useRouter } from "next/router";
// import { useState, useEffect } from "react";


// export default function HomePage () {
//   const router = useRouter();
//   const [isComingFromSplash, setIsComingFromSplash] = useState(false);

//   useEffect(() => {
//     // Detectamos si venimos desde "/" (Splash)
//     if (router.asPath === "/home" && document.referrer.endsWith("/")) {
//       setIsComingFromSplash(true);
//     }
//   }, [router.asPath]);

//   return(
//     <>
//     {/* <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head> */}
//     {isComingFromSplash ? (
//         <Home4 /> // Renderiza sin animación si viene desde "/"
//       ) : (
//         <PageTransition2>
//           <Home4 />
//         </PageTransition2>
//       )}
//     </>
//   )
// };