"use client"

import ArtistProfile from "@/components/Artist";
import ArtistProfile2 from "@/components/Artist/index2"; // *
import ArtistProfile3 from "@/components/Artist/index3";
import ArtistProfile4 from "@/components/Artist/index4";
import ArtistProfile5 from "@/components/Artist/index5";
import ArtistProfile6 from "@/components/Artist/index6"; // *
// import ArtistProfile2 from "@/components/Artist/index2";
import PageTransition2 from "@/components/Layout/Page_Transition2";

export default function Artist() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <PageTransition2>
        <ArtistProfile6 />
      </PageTransition2>
    </>
  )
}