// import { useRouter } from "next/router";
// import { useState, useEffect } from "react";
// import { doc, getDoc } from "firebase/firestore";
// import { db } from "@/utils/firebaseConfig";

// const ArtistProfile = () => {
//   const router = useRouter();
//   const { id } = router.query; // Obtener el ID dinámico desde la URL
//   const [artist, setArtist] = useState(null);

//   useEffect(() => {
//     const fetchArtist = async () => {
//       if (!id) return; // Esperar hasta que se cargue el ID
//       try {
//         const docRef = doc(db, "roster", id);
//         const docSnap = await getDoc(docRef);
//         if (docSnap.exists()) {
//           setArtist(docSnap.data());
//         } else {
//           console.error("No such artist!");
//         }
//       } catch (error) {
//         console.error("Error fetching artist data:", error);
//       }
//     };

//     fetchArtist();
//   }, [id]);

//   if (!artist) {
//     return <p>Loading...</p>;
//   }

//   return (
//     <div className="p-4">
//       <h1 className="text-4xl font-bold">{artist.artist_name}</h1>
//       <img src={artist.artist_img || "/images/IMG-20250115-WA0008.jpg"} alt={artist.artist_name} />
//       <p>{artist.artist_bio}</p>
//     </div>
//   );
// };

// export default ArtistProfile;
// import Head from 'next/head'

"use client"

import ArtistProfile from "@/components/Artist";
// import ArtistProfile2 from "@/components/Artist/index2";
import PageTransition2 from "@/components/Layout/Page_Transition2";

export default function Artist() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <PageTransition2>
        <ArtistProfile />
      </PageTransition2>
    </>
  )
}