"use client";

import PageTransition2 from "@/components/Layout/Page_Transition2";
import ArtistProfile10 from "@/components/Artist/index10";

import { doc, getDoc } from "firebase/firestore";
import { db } from "@/utils/firebaseConfig";

export default function Artist({ artistData }) {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <PageTransition2>
        <ArtistProfile10 data={artistData}/>
      </PageTransition2>
    </>
  )
}

export async function getServerSideProps(context) {
  const { id } = context.params;

  try {
    const docRef = doc(db, "roster", id);
    const docSnap = await getDoc(docRef);

    if (!docSnap.exists()) {
      return { notFound: true };
    }

    return {
      props: {
        artistData: docSnap.data(),
      },
    };
  } catch (error) {
    console.error("Error fetching artist data:", error);
    return { notFound: true };
  }
}